### ISSUE TITLE
Request: auto-close process palette if launched process finished successfully

### ISSUE THREAD

**Issue by mchels** [morassman/process-palette#12]
Is it possible to add an option to have the process-palette panel close automatically if the launched process terminates with exit code 0?

**Comment by morassman** [comment]
That's a good idea! It's kind of the opposite of the `autoShowOutput` option. I'll add something to that effect in an upcoming update.

**Comment by morassman** [comment]
v0.5.2 was just released. It supports a new property called `autoHideOutput`. The default is `false`. If it's `true` then the panel will be hidden if the exit code is 0. It will also only hide if that process' output is currently being shown. The reasoning is that, if you're looking at something else, you probably wouldn't want the panel to hide due to another process that completed in the background.

**Comment by mchels** [comment]
Great. I just checked it and it works fine for me. Thanks!
