### ISSUE TITLE
Input variable doesn't work.

### ISSUE THREAD

**Issue by jshn** [morassman/process-palette#24]
Hi,

I really appreciate your plugin, very nice! :)

Input variable doesn't seam to work. I've tried several inputs but no luck.
I specify in settings ex.: "Name: userinput Message: test: Default value (optional): ttttest"
But when accessing variable $userinput in script I get nothing.

However it works like a charm  when I use Environment Variables.

**Comment by jshn** [comment]
Sorry! Now I got it. Needed to specify the input variable in environment variables also.

**Comment by morassman** [comment]
Thanks @jshn. I'm glad you're finding it useful!

I should probably make it more explicit in the documentation, but environment variables are referenced the way one usually does from the terminal with a $ sign, but all Process Palette variables are referenced by enclosing them in braces, { and }

If you want userinput to be typed in by the user then it will be treated as a Process Palette variable, which means that you should use {userinput} instead of $userinput. It should be _either_ a PP variable _or_ an env variable.

Here's an example:

**Shell Command**
`echo "{TestInput}" $TestEnv`
**Environment Variables**
- Name: TestEnv
- Value: World

**Input Dialogs**
- Name: TestInput
- Default value: Hello

Running the command will give `Hello World`

**Comment by jshn** [comment]
Aha, I see! Of course, that make sense. :)

Many thanks!

**Comment by sebastiendan** [comment]
Hi,

I also want to thank you for your awesome module!
I have a comment related to your answer here: the use of input variables does not work if your command runs an external script. For instance, if you write `echo "{TestInput}" $TestEnv` in a script.bash and then create a command in process-palette executing `npm run script.bash`, then user inputs won't be accessible from within the script.

This is a problem for me because I wanted to add a process-palette command executing my npm scripts such as `build` or `deploy` which use user inputs.

Do you have any solution for this?

Thanks!

**Comment by morassman** [comment]
Hi @sebastiendan. You're welcome!

The input variables is a Process Palette concept, so it only exists within the context of Process Palette. Environment variables, on the other hand, exist within the shell. So what might work for you is to map an input variable to an environment variable.

**Example - Passing an input variable to npm via an environment variable**
Let's say you have the following in your package.json:

``` json
  "scripts": {
    "output": "echo $MYVAR"
  }
```

In Process Palette you can then create a command with:

Shell command : `npm run output`

Create an input variable and map it to an environment variable as shown in the screen shot:

![image](https://cloud.githubusercontent.com/assets/13697130/18676162/faf0af30-7f54-11e6-9c84-0611172bfaae.png)

When running the command you will be prompted for input. That input will be assigned to `MYINPUT`, which in turn will be assigned to `MYVAR`. You should now be able to use `MYVAR` in npm and any bash script.

Hope this works for you!
