### ISSUE TITLE
Request: ability to add commands to main package menu

### ISSUE THREAD

**Issue by philip** [morassman/process-palette#35]
This feature request is for an option to add defined commands to the "Process Palette" packages menu in atom, likely underneath "Reload Configuration". 

I suspect "Action Name" would be displayed there, along with "Keystroke".

**Comment by morassman** [comment]
Hi @philip 

Looking Atom's API it seems to be possible to make changes to the menus during runtime. I'll check it out and include this in the next update.

**Comment by morassman** [comment]
I just released v0.12.0. In the editor, under the General section at the top, you will see a place where you can configure a menu for that command.

I opted to rather do it on a per-command basis instead of putting everything in the same place. This way one will have more control.

It's quite simple. The menu is just a comma separated list of names. The first one being the root and the rest its sub menus. With this approach you can put the command anywhere you like. You can even create a top level menu to make access easier.

**Comment by philip** [comment]
@morassman Nice, thanks. 

Your implementation is much better than I imagined was possible here, which was to essentially toggle a "Packages,Process Palette" root menu on or off.

The only suggested improvement is to expand the description / documentation a bit. The current description:

> A comma separated list of menu names like **Processes, Global**

Granted the behavior becomes obvious after one try, but consider one of the following alternatives:

> A comma separated list of menu and submenu names like **Processes, Global**

Or:

> Menu location for this command, as a comma separated list of menu names. The first name is the top level menu in Atom, followed by sub menus. All non-existent menus are created. The _Action Name_ is inserted into the last menu. Example: **Processes, Global**

**Comment by morassman** [comment]
Yeah. In the UI I try to keep the descriptions short, but I guess this one was a bit too concise :)

Sure! I'll update it to be more descriptive. I'll include it in the next release.
