### ISSUE TITLE
Command execution does not complete if a new program/window is launched

### ISSUE THREAD

**Issue by abid-mujtaba** [morassman/process-palette#4]
I am using process-palette to run a make command that ends by launching the created pdf in mupdf (a new window is opened). Even though the make command for launching mupdf ends with an '&' process-palette considers the command to be still running until such time as the window is closed. Only after the window is closed does the output of the command appear.

A simple way to test this is to run a command that opens a window, and then try to run the same command again. process-palette refuses to do so because it deems that the original command is still running.

**Comment by morassman** [comment]
This is currently the expected behaviour, but not necessarily set in stone. The original intent was to run a command that finishes quickly and then take care of the output. Since there is actually a use case for longer running processes I will look into adding support for it.

Thank you for your detailed description!

**Comment by morassman** [comment]
I started looking at this and would just like to get some clarity it. Was the major concern that output is only produced after the window is closed or was it that only one instance of a process is allowed to run at a time?

A note on &: Since this causes the process to run in the background it is technically not yet complete. The state of the process is therefore correctly reflected. It's just a hinderance since it prevents another instance from being launched. The way I plan on addressing this is to allow multiple instances to be accommodated. If the command is configured to output to the panel then each instance will have its own output panel associated with it.

**Comment by abid-mujtaba** [comment]
The major concern is based on a difference of opinion about what backgrounding a process entails. In my opinion if one has used & it means that the calling process no longer cares what the backgrounded process is doing or when it exits. It justs jumps to the next command. So the calling instance should terminate even if backgrounded processes are present.

However allowing multiple instances to run does alleviate this issue.

**Comment by morassman** [comment]
I agree. My expectation would be the same. In this case, however, all commands are delegated to a third party package, which in turn delegates it to the OS's shell. How commands are executed and symbols interpreted are therefore outside of my hands.

Another option is to add a flag to a command's configuration to indicate that it should run as a background process. When one then runs a command it will execute and then immediately allow another one to be started.

**Comment by abid-mujtaba** [comment]
Fair enough. The flag in the command configuration should work.

**Comment by morassman** [comment]
v0.5.0 allows multiple instances of a process to run at the same time, which should help with this particular issue.
