### ISSUE TITLE
process-palette crashes Atom 1.18.0 when cursor not in document

### ISSUE THREAD

**Issue by stefanvollmar** [morassman/process-palette#45]
There is a very annoying effect which might be related to recent changes in Atom and which is probably easy to fix (if it is a bug in Atom it might be easy to circumvent) - this, unfortunately, is a "show-stopper" class problem: our scripts rely on arguments build from the immensely useful "{file*}" type of variable (this might be important). Everything works as expected (and extremely well!) when the cursor is placed in an active document. However, if the focus (cursor) is within the left-hand tree of files and a process-palette action is triggered via keyboard shortcut or menu entry - Atom 1.18.0 will crash. *Many* thanks in advance for fixing this (or providing a workaround).

**Comment by morassman** [comment]
This is pretty bad. Packages should never cause Atom to crash.

I haven't been able to reproduce this though, but maybe you can help me debug. There might be something small I'm missing. I'm also using Atom 1.18.0 and I use OSX 10.11.6. What OS are you using?

I defined a simple command that uses all of the {file*} variables

```bash
echo '{fileExt} {fileName} {fileNameExt} {filePath} {fileDirPath} {fileAbsPath} {fileDirAbsPath} {fileProjectPath}'
```

and then tested as shown below.

**Test with editor having focus**
Running the command when the editor has focus produces the expected output. All of the variables were resolved and injected correctly.

**Test with project view having focus**
Clicked on a folder in the project tree so that it gets focus. Running the command then via a shortcut key produced no output. None of the variables have values and the output panel is just blank. Atom, however, didn't crash.

Is it possible that the particular command that you are running will fail if any of the {file*} variables resolve to an empty value? In general this shouldn't be a problem. All errors produced by child processes are captured by Process Palette and reported back to the user.

Having said that. It _has_ happened to me before though that running a command caused Atom to crash instead of the error being captured. Unfortunately I can't remember what the command and its arguments were. I'm guessing now, but it may be that a child process that crashes _can_ crash in such a way that the parent process (Atom in this case) crashes as well.

Thus far, the only thing I can think of is that the {file*} variables resolving to empty values are problematic for the command you are running. Why it's causing Atom to crash is still a mystery. 

Try the following and see what happens. Take the command you want to run and manually replace all the {file*} instances with empty values. Then run that command from the terminal and see what happens.

**Comment by stefanvollmar** [comment]
Thanks for the fast response. I can reproduce the problem on MacOS 10.12.5.
This is the kind of thing that would happen with {file*} resolving to empty values:

```
jeeves:md-one stefan$ python '/scripts/gm.py' --pdf ''
python: can't open file '/scripts/gm.py': [Errno 2] No such file or directory
```

This is the relevant part of my process-palette.json file:
```
...
"commands": [
    {
      "namespace": "Process Palette",
      "action": "Make PDF",
      "command": "python '{fileProjectPath}/scripts/gm.py' --pdf '{fileAbsPath}'",
      "arguments": [],
      "cwd": "{fileDirAbsPath}",
      "inputDialogs": [],
      "env": {},
      "keystroke": "f1",
      "stream": false,
      "outputTarget": "panel",
      "outputBufferSize": 80000,
      "maxCompleted": 3,
      "autoShowOutput": false,
      "autoHideOutput": false,
      "scrollLockEnabled": false,
      "singular": false,
      "promptToSave": true,
      "saveOption": "all",
      "patterns": [
        "default"
      ],
      "successOutput": "{stdout}",
      "errorOutput": "{stdout}\n{stderr}",
      "fatalOutput": "Failed to execute : {fullCommand}\n{stdout}\n{stderr}",
      "startMessage": "Now processing: \n{fileNameExt}\nThis can take a few seconds...",
      "successMessage": "Conversion to PDF of\n{fileNameExt}\nfinished successfully.",
      "errorMessage": "{stderr}",
      "fatalMessage": "Failed to execute : {fullCommand}\n{stdout}\n{stderr}",
      "menus": [
        "MPI-SF"
      ],
...
```
there is a number of other places where we use {file*} - if it is indeed just empty, it should not be a problem - can you reproduce the problem? It seems to me that it is probably not anything in the "command" parameter where I also would have looked first (however, this should at least make it easier to reproduce).

**Comment by morassman** [comment]
Thanks! It was very helpful to see your whole config. I was able to reproduce it now. The problem is when the cwd is empty. I've never tested it before with an empty value, but it would be easy to fix.

I tested a bit more and found that the cwd behaviour is rather strange. Any non-empty cwd works. A valid path succeeds and an invalid path simply logs an error to the console. An empty cwd, however, causes the crash you've been seeing. What's strange is that an exception isn't even thrown, so there's no way to handle this. Atom simply crashes.

I think what I'll do is to just _not_ set the cwd when the value is empty so that the default value is used.

There's another change to Process Palette that has been made that I still need to test, but once I've done that I will release a patch with the fix for the cwd.

**Comment by stefanvollmar** [comment]
Excellent, thanks!

**Comment by stefanvollmar** [comment]
Sorry, on second thoughts your proposed solution is, naturally, quite an improvement, however, not ideal for us (and probably others): in all cases where I triggered the process-palette shortcut and the mouse focus was somewhere in the left-hand file tree, this was accidental and I expected something else to happen (the correct document was open). A better solution would be for process-palette to force the focus on the first available document window before executing the configured command. Alternatively, maybe have a configurable, optional warning message if an action is triggered when no document has a focus?

**Comment by morassman** [comment]
The same thing occurred to me afterwards as well. It won't be a good idea to change the cwd behind the scenes when one was explicitly specified.

Forcing the focus wouldn't be necessary. Atom's API allows one to determine which editor is currently visible. It gets ambiguous though when the workspace is split into multiple parts where each has its own currently visible editor. I think what would be better is to see if there is one, and only one, editor visible and then use its {file*} variables for the command. If there is more than one editor visible and none of them has focus then a warning can be displayed.

**Comment by stefanvollmar** [comment]
Very good, thanks!

**Comment by morassman** [comment]
I've released version 0.13.0 with a fix for this.

It turned out slightly different from what I planned. As I mentioned before, Atom's API allows one to determine how many editors are visible at a time. This number will only be more than one when the workspace has been split up. Of these visible editors, only one of them can be active at a time. It's this active editor that will be the target of the command being executed.

It turns out though that Atom regards the last editor that was used as active **whether it has focus or not**. In your use case this means that, even though the project tree has focus, the last editor you used is considered the active one and the command will therefore be applied to that editor. In general I think that this behaviour would be expected, especially if the workspace hasn't been split into multiple panes and there is only one editor visible.

When the workspace _has_ been split and there _are_ multiple visible editors everything will still work without a problem. The only thing is that one must then know which of the visible editors is the _active_ one. This is obvious when you're busy editing in one, but not necessarily when something like the project tree has focus. It may just be a UI related thing, but with the theme I use (Atom Dark), there is no visual indicator to show which editor is the active one apart from the file being highlighted in the project tree. I personally don't think that this would be a big deal for the typical use case though.

**Comment by stefanvollmar** [comment]
Many thanks for this new release - it solved our problem beautifully.

**Comment by morassman** [comment]
Sure. You're welcome. Thanks for your inputs and helping to debug it!
