### ISSUE TITLE
stdout should use Courrier font

### ISSUE THREAD

**Issue by pcarbonn** [morassman/process-palette#51]
or any fixed width font.
Otherwise, output that rely on it fail.

**Comment by morassman** [comment]
The output panel uses the font family that is configured for Atom's editor. The text editor is typically configured with a fixed-width font, which is why the one from the editor is used. I tested it and it seems to fail if a font isn't explicitly specified. This never used to be the case, so something may have changed in a recent Atom update that returns a different value when asking for the font.

I'll fix this for the next version.

**Comment by pcarbonn** [comment]
Sounds great. Thanks.

**Comment by morassman** [comment]
This should not be a problem anymore in the latest version.

**Comment by pcarbonn** [comment]
Yes, it works ok, now. Thanks !
