### ISSUE TITLE
Cannot scroll console output

### ISSUE THREAD

**Issue by adeemij** [morassman/process-palette#52]
After updating to 0.15.1, output in the console window does not respond to vertical scrolling.

No response to 1) mouse wheel 2) dragging a selection to window borders.
Arrow keys will scroll output horizontally, but not vertically.
Can confirm there is more output by resizing the output pane.

This particular command is a windows batch file.

Windows 7 64-bit, everything in atom up to date.

**Comment by morassman** [comment]
Hi @adeemij. Sorry about introducing such a bug. I develop on OSX and it doesn't have this problem, so I wasn't aware of it.

I'll get a Windows 7 installation up and see if I can reproduce the problem

**Comment by adeemij** [comment]
No worries - bugs happen.  Please let me know if there is additional information I can provide.

(Also - I noticed the release notes list the current version as 0.14.1, while the plugin info lists 0.15.1.)

**Comment by morassman** [comment]
Yeah. I saw that the version was wrong *just* after deploying. I've changed
it, but I don't want to deploy just to fix it. I was kinda hoping no one
would notice :)

PS. It's actually not the first time that this has happened. Editing the
change log is always the last thing I do, but I sometimes forget to commit
it before deploying.

**Comment by sjurgis** [comment]
Scroll is broken on macOs too!
Strangely horizontal scrolling works fine.

**Comment by morassman** [comment]
That is very strange. I work on a mac and I tested on Windows 7 as well and it worked properly on both.

I've experienced in the past that the new CSS of a package doesn't apply properly after updating the package. This is probably a poor suggestion, but if you haven't restarted Atom since updating the package then just restart it and see if it still happens.

**Comment by adeemij** [comment]
I can confirm that the bug still exists after restarting everything.

Can you point me toward the files you think are not being updated?  I can check if they are as expected.

**Comment by morassman** [comment]
Thanks for checking. If the restart didn't fix it then it won't be an update issue. As far as I understand the update issue is when the previous version's CSS is still in memory and being used instead of the new CSS, but after restarting that won't be the case anymore.

I'll see what I can do, but not being able to reproduce this myself makes it a bit hard. This issue came in when I started using the dock, so I'll go look at what exactly changed and see if I can find the issue that way.

**Comment by morassman** [comment]
What theme are you using? I just want to make sure I test with the same environment.

**Comment by adeemij** [comment]
I'm using the One Dark theme.

**Comment by sjurgis** [comment]
One Dark here too.

**Comment by morassman** [comment]
Thanks for letting me know!

I tested with One Dark, but was still unable to reproduce the problem. I tested on Windows 7 64-bit and on OS X El Capitan.

I went through the UI and styling and cleaned it up a bit. Since I cannot reproduce the problem I don't know whether the scrolling issue would be fixed or not. Please update to v.0.15.2 and test again.

This is another poor suggestion, but if the problem persists then uninstall the package and reinstall it. I'm sure the update process works properly, but it's worth a try. If it still doesn't work then I will need someone to help me debug it.

**Comment by adeemij** [comment]
The update has solved the issue for me; no reinstallation was necessary.  Thanks for your timely efforts in figuring this out!

**Comment by sjurgis** [comment]
Likewise. I can finally scroll clearly now the rain has passed!

Btw, is there a way to have a reverse scroll or enable terminal colours?

**Comment by morassman** [comment]
Great! I'm glad to hear it's working now for everyone.

@sjurgis, I'm not quite sure what you mean by reverse scroll? If this is a new feature then rather log a new issue with a description of the behaviour you are looking for.

As for terminal colours. Functionality to interpret ANSI escape sequences and apply the specified styles was implemented in [this](https://github.com/morassman/process-palette/pull/13) pull request. You can actually test it by running the following from Process Palette:

```
printf "\033[31mRed\033[0m\n"
```

However. There is one catch. Commands do not always produce output with escape sequences, especially if what they are writing to is not a terminal. Process Palette is not a terminal emulator, which means that some commands that produce colours in the terminal will not necessarily produce those colours in Process Palette. I've looked into this and I'm not sure if there is something I can do about it.

**Comment by sjurgis** [comment]
@morassman Sorry, I meant to have have terminal output reverse - latest/last line to be on top.

**Comment by morassman** [comment]
Ok I understand now. I must say, this is an unusual request :) The output automatically scrolls to the bottom, so you'll always be able to see the last line, just not at the top. I really don't think I'm going to be adding this ability though.

**Comment by adeemij** [comment]
Just confirming that the scroll behavior is still working as expected for me as well.
