### ISSUE TITLE
Continue to display warning bubble until it is dismissed

### ISSUE THREAD

**Issue by Pauan** [morassman/process-palette#6]
When the command fails, process-palette displays a warning bubble: [(screenshot)](http://i.imgur.com/YqpzqmI.png)

The problem is, after a few seconds it automatically disappears, even if I'm hovering my mouse over the bubble.

This is not enough time to read the error message, which means I have to always look at the bottom pane (in which case, why even bother with the warning bubble?).

I'm not sure if Atom will allow you to do this, but it would be nice to have the warning bubble continue to display until it is dismissed (e.g. by a left click).

This should only apply to the warning bubble: the success bubble should automatically fade after a few seconds.

**Comment by morassman** [comment]
The notification used for fatal messages has this behaviour. It requires one to dismiss the message manually. As far as I know one cannot configure Atom's warning notification to have a dismiss button. If it's possible then I'll do that, otherwise I can use the same type of notification for warnings as I do for fatals. They will both be red, but at least one can dismiss them both manually.

**Comment by Pauan** [comment]
That sounds like a good solution to me.

In my opinion, Atom should also require manual dismissal for warnings, but as you say, that's outside of your control.

**Comment by morassman** [comment]
It turns out that notifications are configurable so that they require to be dismissed. This is not documented in Atom's API, but I could derive it from looking at the implementation. Warning messages are now configured in this way an requires the user to explicitly dismiss them.

**Comment by Pauan** [comment]
I just upgraded to version 0.5.0, and it's working, thanks!
