### ISSUE TITLE
Scroll lock is on - even though I set it to "OFF"

### ISSUE THREAD

**Issue by hang-on** [morassman/process-palette#60]
Hi. I recently updated, and it resulted in scroll lock being always ON, regardless what I do?!

**Comment by morassman** [comment]
Issues with scroll lock have been reported before. For some reason I've never been able to reproduce the problem and yet there are a few people experiencing it. Without being able to reproduce the issue it's really hard to debug.

I'm actually considering adding a setting so that one can choose whether scroll lock should auto-enable at all.

**Comment by hang-on** [comment]
The problem comes and goes for me. I don’t think it is the update anymore - to me it seems it might be related to the messages from my assembler being output to the window. Some warnings seem to trigger a scroll lock, while others don’t. Could it be that the window recieves a scroll lock (or something it interprets as a scroll lock) from the output? That might explain stuff. Thanks for a great program by the way, it really helps in my retroprogramming flow :)

Sendt fra min iPhone

**Comment by morassman** [comment]
This is related to issue [19](https://github.com/morassman/process-palette/issues/19). I'm therefore going to close this one. See my latest comment on that issue. The problem may have been fixed with the latest update.

**Comment by morassman** [comment]
Thanks @hang-on. I'm glad that you find it useful!

The scroll lock handling code responds to three things:
1. When the user clicks on the output.
2. When the user scrolls.
3. When additional output is appended.

What I found was that a scroll event is also fired when output is appended. I was under the impression that a scroll event is only fired when the user performs a scroll. To distinguish between these two one needs to listen for mouse wheel events as well. The update distinguishes between these two now with the behaviour each one needs. I think that's where the bug came in, so hopefully this resolves the issue.
