### ISSUE TITLE
Better warning bubble when stream is set to true

### ISSUE THREAD

**Issue by Pauan** [morassman/process-palette#7]
Here is how it looks when I run the command with `stream` set to `false`: [(screenshot)](http://i.imgur.com/YqpzqmI.png)

Here is how it looks when I run the command with `stream` set to `true`: [(screenshot)](http://i.imgur.com/1H6d1aA.png)

Ideally they would both show the full error message.

I haven't looked at how process-palette is implemented, and maybe it's difficult to implement, but perhaps it would be possible to store the stdout and stderr while streaming, and then display it when the command finishes?

**Comment by morassman** [comment]
This behaviour is intentional, but it can be changed. When stream is set to true the output is sent directly to the output target without being accumulated. The reasoning was that one would see the output anyway. The change was also made to conserve memory in order to prevent the output from being both streamed and accumulated at the same time.

The behaviour actually used to be exactly how you suggest it to be, in fact, that is how it is when stream is false. I will change it back, but for the sake of memory usage I'll allow a buffer size to be configured to prevent the accumulated output from getting out of hand.

**Comment by Pauan** [comment]
I think a buffer is a great idea. After all, the warning bubble is fairly small, so it doesn't make any sense to accumulate a huge buffer anyways, since you'll only be displaying a fixed amount of information.

**Comment by morassman** [comment]
The behaviour was changed back to how it used to be. The stdout and stderr are both buffered regardless of whether stream is set to true. These variables can therefore now always be used. A property called `outputBufferSize` is now also available to configure buffer size.

**Comment by Pauan** [comment]
I just upgraded to version 0.5.0, and it's working, thanks!
