### ISSUE TITLE
Cannot execute python script on windows

### ISSUE THREAD

**Issue by calebmeyer** [morassman/process-palette#78]
I just installed this awesome package, and I've been following the readme. I created a python file, hello.py, which just contains `print('hello world')`. I created a new command, which you can see in
https://gist.github.com/calebmeyer/92ea96345ddafd84fd8d4874d816b882

I checked for python in both powershell and cmd.exe, I can see it:
![image](https://user-images.githubusercontent.com/3342777/54316711-6f469200-45af-11e9-9899-a7dbae577191.png)
![image](https://user-images.githubusercontent.com/3342777/54316725-766da000-45af-11e9-9d7f-ca39d49247cc.png)

I went to run my python file with the default (which looks to be cmd.exe on windows) and got an error:
![image](https://user-images.githubusercontent.com/3342777/54316800-900ee780-45af-11e9-881e-0a2bdf6a1e8a.png)

I changed from the default to point explicitly to powershell by changing the shell to `C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
Then I tried to run the command again, and get a different error:
![image](https://user-images.githubusercontent.com/3342777/54316873-b9c80e80-45af-11e9-8a4d-f49529656786.png)

Any idea what I can do to fix my setup? I really like this package, it's awesome what you've got here.
Versions and dotfiles for reference:
```
>apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 3.7.2
git 2.16.2.windows.1
visual studio

Windows 10 Enterprise version 10.0.17134 Build 17134
```
https://gist.github.com/calebmeyer/57593e1d220fef2910e3d881852a04b3

**Comment by calebmeyer** [comment]
Defaults example (in powershell, which I'd prefer to use)
![image](https://user-images.githubusercontent.com/3342777/54317049-34912980-45b0-11e9-9ef3-0384becbec51.png)

Echo example:
![image](https://user-images.githubusercontent.com/3342777/54317076-41158200-45b0-11e9-854b-c7c38064b684.png)

Stream example:
![image](https://user-images.githubusercontent.com/3342777/54317095-4d014400-45b0-11e9-841a-512ba32ce3d4.png)

**Comment by calebmeyer** [comment]
Well, it looks like I just needed to do a restart of my computer to get windows to recognize the new PATH changes.

**Comment by calebmeyer** [comment]
If you have time to look into the extra characters getting inserted into powershell commands, I'd love to hear back!

**Comment by morassman** [comment]
Hey Caleb. I'm glad you got the issue with the path sorted out.

I haven't used Windows in a long time and I've never used powershell before. I don't know where those extra characters come from, but it might be an issue with the underlying package that is used for running the shell commands.

I'll see what I can find out. I read up a bit and found a possible workaround that you can maybe use for now. You can run powershell commands from the normal `cmd.exe` shell. Take the **stream-example** configuration, for instance, and change its command to `powershell -command "ping localhost"`

You basically invoke powershell and then put in double quotes the command you'd like it to run.

In process-palette's own configuration, just remove `C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe` again so that the default can be used.

**Comment by calebmeyer** [comment]
Good call. I didn't know the syntax for passing a command to powershell like that (with bash and fish it's just `-c`. Thank you!
