### ISSUE TITLE
Processes still running after killing running process in process-palette 

### ISSUE THREAD

**Issue by Pauan** [morassman/process-palette#8]
I have a command `npm run-script watch` which automatically recompiles my project when any of my files are changed.

This is a long-running process that will keep executing until it is manually killed.

When I run it in a terminal, it creates the following processes, in this order:

```
npm
sh -c npm install && webpack --watch
```

When I use `Ctrl-C` to kill the process, both processes are killed.

---

However, when I run the same command in process-palette, the following processes are created:

```
/bin/sh -c npm run-script watch
npm
sh -c npm install && webpack --watch
```

When I kill the process in process-palette, it kills this process:

```
/bin/sh -c npm run-script watch
```

But the other 2 are **not** killed:

```
npm
sh -c npm install && webpack --watch
```

If I try running it again, it creates new processes, so now there are even more unused processes:

```
npm
sh -c npm install && webpack --watch
npm
sh -c npm install && webpack --watch
```

Leaking processes like this is bad.

---

Some additional information: I'm on Debian GNU/Linux 64-bit.

Atom version 1.0.11, process-palette version 0.4.12

This is the parent-child relationship of the processes:

```
/usr/share/atom/atom
|__ /bin/sh -c npm run-script watch
   |__ npm
      |__ sh -c npm install && webpack --watch
```

**Comment by morassman** [comment]
This is quite severe. I looked into it and was able to find the problem. The solutions are varied and unfortunately also different depending on the OS, but the problem at least seems solvable. I'm on the brink of making a release that I've been working on for a while, so I'd like to get it out the door. If I don't get round to fixing this in that release then I'll do it as a smaller updated soon after.

PS. Thanks for the detailed description. It's very helpful!

**Comment by Pauan** [comment]
[term](https://atom.io/packages/term) uses [pty.js](https://github.com/chjj/pty.js) to spawn its processes. Perhaps that would help?

**Comment by morassman** [comment]
I've implemented a solution that I've tested on OSX 10.10.4 and Ubuntu 14.04. It ensures that the child processes are killed along with the parent process. It works for this particular case, "commandA && commandB".

What it doesn't work for are commands that are run with "command&". I'm struggling to get the process IDs of child processes spawned in this way. One thing that I've tried is to kill the processes with the same group ID, but that turned out terminating Atom as a whole. For now I'm logging this as a known issue.

Please test with v0.5.0 and let me know if you are now able to terminate the process tree. I will close this issue once I know the solution works for you.

**Comment by Pauan** [comment]
I just tested with v0.5.0, and all the processes are correctly terminated, thanks!

**Comment by morassman** [comment]
Glad to hear!
